Global:
  device: cuda
  character_dict_path: ./datasets/icdar15/ic15_dict.txt

Optimizer:
  lr: 0.0005

Train:
  dataset:
    name: cidar15
    data_dir: datasets/icdar15/train
    label_file_list: ["./datasets/icdar15/rec_gt_train.txt"]
    transforms:
      image_shape: [3, 32, 320]
      augmentation: True

  loader:
    epochs: 100
    shuffle: True
    batch_size: 64
    num_workers: 8
    use_shared_memory: False

Eval:
  dataset:
    name: cidar15
    data_dir: datasets/icdar15/test
    label_file_list: ["./datasets/icdar15/rec_gt_test.txt"]
    transforms:
      image_shape: [3, 32, 320]
      augmentation: False

  loader:
    shuffle: False
    batch_size: 64
    num_workers: 4
    use_shared_memory: False

Debug:
  transforms: debugs/transformation
  log_file: 'logs/crnn.log'
  tensorboard: debugs/tensorboard
